version: '3.9'

services:
  postgres:
    image: postgres:15.4
    ports:
      - 5432:5432
    volumes:
      - pg_data_local:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      # - POSTGRES_USER=postgres

volumes:
  pg_data_local:
    driver: local
