concurrent = 8
check_interval = 0

[session_server]
  session_timeout = 3600

[[runners]]
  name = "docker-runner-01"
  url = "https://gitlab.com/"
  token = "YOUR_RUNNER_TOKEN"
  executor = "docker"
  request_concurrency = 4
  tag_list = ["install-autoscale", "test-autoscale", "build-autoscale", "deploy-autoscale", "release-autoscale", "shared-autoscale"]

  [runners.custom_build_dir]

  [runners.cache]
    # Type = "local"
    Path = "/cache"
    Shared = true

    [runners.cache.local]

  [runners.docker]
    tls_verify = false
    image = "ubuntu:24.04"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
    shm_size = 2147483648

    cpus = "1"
    memory = "2g"
    memory_swap = "2g"
    memory_reservation = "1g"

    network_mode = "bridge"
    pull_policy = ["if-not-present"]
    helper_image = "gitlab/gitlab-runner-helper:ubuntu-x86_64-v18.5.0"

  [runners.docker.tmpfs]
    "/tmp" = "rw,noexec,nosuid,size=512m"
    "/run" = "rw,noexec,nosuid,size=512m"
