# version: "3.8"
services:
  mysql-n1:
      build: .
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: admin
      volumes:
      - mysql-data-n1:/var/lib/mysql
      ports:
      - "3306:3306"

  mysql-n2:
      build: .
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: admin
      ports:
      - "3307:3306"
      volumes:
      - mysql-data-n2:/var/lib/mysql

  mysql-n3:
      build: .
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: admin
      ports:
      - "3308:3306"
      volumes:
      - mysql-data-n3:/var/lib/mysql

volumes:
  mysql-data-n1:
    driver: local
  mysql-data-n2:
    driver: local
  mysql-data-n3:
    driver: local
