services:
  mysql:
    image: mysql:8.0-bookworm
    command:
        --default-authentication-plugin=mysql_native_password
        --bind-address=0.0.0.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3306:3306'
    volumes:
      - mysql8_db:/var/lib/mysql
volumes:
  mysql8_db:
    driver: local
