version: "3.8"

networks:
  default:
    name: percona-nw
    driver: bridge

volumes:
  percona-data:
    driver: local

services:
  percona:
      container_name: percona
      image: percona:8.0.34-26-centos
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: admin
      volumes:
      - percona-data:/var/lib/mysql
      ports:
      - "3306:3306"
