services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    #image: mcr.microsoft.com/mssql/server:2017-CU11-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_SA_PASSWORD: "PASS"
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
