services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'adminminio'
      MINIO_ROOT_PASSWORD: 'userminio'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data
