#version: '3.9'
services:
  haproxy:
    build: 'haproxy'
    restart: always
    ports:
      - 5432:5432
      - 7000:7000
    depends_on:
      - zoo1
      - pg-master
      - pg-slave1
      - pg-slave2

  zoo1:
    image: confluentinc/cp-zookeeper:latest
    container_name: zoo
    restart: always
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  pg-master:
    build: 'postgres'
    container_name: pg-master
    restart: always
    hostname: pg-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: '/var/lib/postgresql/data/pgdata'
    expose:
      - 5432
      - 8008
    ports:
      - 5433:5432
    volumes:
      - pg_data_master:/var/lib/postgresql/data
    command: patroni /postgres0.yaml
    networks:
      - patroni-net
    depends_on:
      - zoo1

  pg-slave1:
    build: 'postgres'
    container_name: pg-slave1
    restart: always
    hostname: pg-slave1
    expose:
      - 5432
      - 8008
    ports:
      - 5434:5432
    volumes:
      - pg_data_slave1:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: '/var/lib/postgresql/data/pgdata'
    command: patroni /postgres1.yaml
    networks:
      - patroni-net
    depends_on:
      - zoo1

  pg-slave2:
    build: 'postgres'
    container_name: pg-slave2
    restart: always
    hostname: pg-slave2
    expose:
      - 5432
      - 8008
    ports:
      - 5435:5432
    volumes:
      - pg_data_slave2:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: '/var/lib/postgresql/data/pgdata'
    command: patroni /postgres2.yaml
    networks:
      - patroni-net
    depends_on:
      - zoo1

networks:
  patroni-net:
    driver: bridge

volumes:
  pg_data_master:
    driver: local
  pg_data_slave1:
    driver: local
  pg_data_slave2:
    driver: local
