version: '3.7'

services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.4.0
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-admin}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
      # - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
    ports:
      - ${MEILI_PORT:-7700}:7700
    networks:
      - meilisearch
    volumes:
      - meilisearch_db:/meili_data
    restart: unless-stopped

volumes:
  meilisearch_db:
    driver: local

networks:
  meilisearch:
    driver: bridge
